### ISSUE TITLE
Unsplash API Terms of Use violation?

### ISSUE THREAD

**Issue by victorz** [deepjyoti30/QuickWall#8]
Just wondering, because when we create a new Unsplash app, we have to click and agree that the app is not "🚫 a wallpaper app [which] returns Unsplash images for downloading. Without the integration, the app has no content and no value to users."

I'd say that matches this app. I wanted to write one of these applications myself but in Go, but this condition stopped me from going forward with using Unsplash.

Can you or someone with more knowledge verify this isn't the case?

See: [Guideline: Replicating Unsplash](https://help.unsplash.com/en/articles/2511257-guideline-replicating-unsplash)

**Comment by victorz** [comment]
https://github.com/deepjyoti30/QuickWall/blob/973b44c3e6e2cecf51486c39c4b11dcf448e53d8/QuickWall/wall.py#L27

We're also made to agree to this term:

![image](https://user-images.githubusercontent.com/7494/68550337-40b0dd80-0402-11ea-9bf1-e3f2743ff61d.png)

**Comment by deepjyoti30** [comment]
Hey @victorz , I'm aware that my access key is openly available but unsplash also has a rule that the users should not have to create their own keys in order to use the app anf currently I don't know how I can make user's use my key and keep it secret too at the same time.

Regarding the other issue, thanks for the heads up. I'm aware that Unsplash asks not to copy the core functionality and that is why I'm trying to add other functions to the app.

**Comment by victorz** [comment]
Sorry to file this issue on your project -- I was actually mostly interested in what this would mean, because I intended to make a similar application myself in Go and wanted to hear your opinion on the subject. :innocent:

But yes, I agree it's definitely a bit difficult to hide API access keys in an interpreted language, if not impossible. Don't worry, I'm not an Unsplash spy or representative, so :zipper_mouth_face: :wink:

Feel free to close at your whim. :+1:
